version: '3'
services:
  # Node.js Server
  notes-development-api:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: my_notes_app-development-api
    env_file:
      - ./src/private/development.env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    networks:
      - my_notes_app_development_network

    depends_on:
      - my_notes_app-development-db
    command: npm run development

# PostgreSQL Database
  my_notes_app-development-db:
    image: postgres:15
    container_name: my_notes_app-development-db
    env_file:
      - ./src/private/development.env
    volumes:
      - my_notes_app-development-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_notes_app_development_network
volumes:
  my_notes_app-development-data:
  
networks:
  my_notes_app_development_network:
    driver: bridge
