# fly.toml app configuration file generated for patient-field-1018 on 2023-09-13T10:58:14-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-field-1018"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
